kind: pipeline
type: docker
name: build-and-publish

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: mhealthvn/${DRONE_REPO_NAME}
      tags: ${DRONE_BRANCH}
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    when:
      event:
        - push
        - tag

  - name: publish
    image: plugins/docker
    settings:
      repo: mhealthvn/${DRONE_REPO_NAME}
      tags: ${DRONE_BRANCH}
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    when:
      event:
        - push
        - tag
