kind: pipeline
type: docker
name: build-and-publish

steps:
  - name: build
    image: plugins/docker:20.18.5
    settings:
      repo: mhealthvn/${DRONE_REPO_NAME}
      tags: ${DRONE_BRANCH}
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    when:
      event:
        - push
        - tag

  - name: publish branch tag
    image: plugins/docker:20.18.5
    settings:
      repo: mhealthvn/${DRONE_REPO_NAME}
      tags: ${DRONE_BRANCH}
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    when:
      event:
        - push
        - tag
        
  - name: publish version tag
    image: plugins/docker:20.18.5
    settings:
      repo: mhealthvn/${DRONE_REPO_NAME}
      tags: ${DRONE_TAG##v}
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    when:
      event:
        - push
        - tag
        
