version: "3.8"

services:
  keycloak:
    # image: bitnami/keycloak:21.1.1
    image: keycloak:local
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN_USER=adminuser
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - DB_VENDOR=POSTGRES
      - DB_ADDR=db
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - KK_TO_RMQ_URL=localhost
      - KK_TO_RMQ_PORT=5672
      - KK_TO_RMQ_EXCHANGE=Keycloak
      - KK_TO_RMQ_USERNAME=admin
      - KK_TO_RMQ_PASSWORD=admin
      - KK_TO_RMQ_USE_TLS=false

    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
